In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Environment Ready")

Environment Ready

In [5]:
occupancy = pd.read_csv("../data/urbanev/occupancy.csv")
volume = pd.read_csv("../data/urbanev/volume.csv")
price = pd.read_csv("../data/urbanev/price.csv")
duration = pd.read_csv("../data/urbanev/duration.csv")

stations = pd.read_csv("../data/urbanev/stations.csv")
time = pd.read_csv("../data/urbanev/time.csv")
information = pd.read_csv("../data/urbanev/information.csv")
distance = pd.read_csv("../data/urbanev/distance.csv")
adj = pd.read_csv("../data/urbanev/adj.csv")

acn = pd.read_excel("../data/acn/acndata_sessions.json.xlsx")

In [6]:
datasets = {
    "occupancy": occupancy,
    "volume": volume,
    "price": price,
    "duration": duration,
    "stations": stations,
    "time": time,
    "information": information,
    "distance": distance,
    "adj": adj,
    "acn": acn
}

for name, df in datasets.items():
    print("\n" + "="*60)
    print(name.upper())
    print("="*60)
    print("Shape:", df.shape)

============================================================
OCCUPANCY
============================================================
Shape: (8640, 248)

============================================================
VOLUME
============================================================
Shape: (8640, 248)

============================================================
PRICE
============================================================
Shape: (8640, 248)

============================================================
DURATION
============================================================
Shape: (8640, 248)

============================================================
STATIONS
============================================================
Shape: (1706, 6)

============================================================
TIME
============================================================
Shape: (8640, 6)

============================================================
INFORMATION
============================================================
Shape: (247, 10)

============================================================
DISTANCE
============================================================
Shape: (247, 248)

============================================================
ADJ
============================================================
Shape: (247, 248)

============================================================
ACN
============================================================
Shape: (16304, 27)

In [7]:
occupancy.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,12,16,24,15,6,8,24,1,2,10,9,5,4,12,5,3,6,17,44,21,5,18,31,14,52,18,3,14,4,24,18,33,47,74,8,21,53,32,90,8,2,43,1,32,4,13,32,28,58,49,94,97,25,75,30,93,46,13,21,19,73,6,6,14,4,51,59,25,9,85,35,4,6,2,1,4,12,91,2,0,2,11,0,9,3,32,8,40,26,19,4,17,28,1,2,120,64,9,12,20,18,15,5,50,12,65,4,53,5,7,28,80,7,2,0,8,61,19,53,34,15,24,15,13,1,24,6,62,49,16,10,3,43,7,46,0,10,99,5,95,91,6,5,20,56,1,9,4,14,7,2,1,25,18,12,2,75,87,6,21,31,87,6,4,18,2,45,1,23,34,10,64,50,60,63,87,29,42,29,63,2,7,29,127,2,27,15,11,16,59,35,10,21,6,47,5,9,21,22,4,39,2,4,0,13,13,25,2,13,2,18,5,3,3,2,5,5,13,6,3,5,14,18,16,4,27,12,53,6,80,2,0,15,16,2,2,38,0,12,1,38,26,162,10,1,8,15
1,2,12,16,24,15,6,8,24,1,2,10,9,5,4,12,5,3,6,17,44,21,5,18,31,14,52,18,3,14,4,24,18,33,47,74,9,21,53,32,90,8,2,43,1,32,4,13,32,28,58,49,94,97,25,75,30,93,46,13,21,19,73,6,6,14,4,51,59,25,9,85,35,4,6,2,1,4,12,91,2,0,2,11,0,9,3,32,8,40,26,19,4,17,28,1,2,120,64,9,12,20,18,15,5,50,12,65,4,53,5,7,28,80,7,2,0,8,61,19,53,34,15,24,15,13,1,24,6,62,49,16,10,3,43,7,46,0,10,99,5,95,91,6,5,20,56,1,9,4,14,7,2,1,25,18,12,2,75,87,6,21,31,87,6,4,18,2,45,1,23,34,10,64,50,60,63,87,29,42,29,63,2,7,29,127,2,27,15,11,16,59,35,10,21,6,47,5,9,21,22,4,39,2,4,0,13,13,25,2,13,2,18,5,3,3,2,5,5,13,6,3,5,14,18,16,4,27,12,53,6,80,2,0,15,16,2,2,38,0,12,1,38,26,162,10,1,8,15
2,3,12,16,24,15,6,8,24,1,2,10,9,5,4,12,5,3,7,17,44,21,5,18,31,14,52,18,3,17,4,24,18,33,46,74,9,21,53,33,89,8,2,52,1,32,4,13,32,28,58,49,94,97,25,75,30,93,46,13,21,19,74,6,6,14,4,51,59,25,9,87,35,4,7,2,1,4,12,94,2,0,2,11,0,9,3,34,8,44,26,19,4,18,28,1,2,120,63,10,12,21,18,15,5,50,12,65,4,53,5,7,28,80,8,2,0,8,63,19,53,34,15,24,15,13,1,25,6,62,49,16,10,3,44,7,46,0,10,99,5,95,91,6,5,20,57,1,10,4,17,7,2,1,30,18,12,2,75,88,6,21,31,87,6,4,18,2,46,1,23,35,10,64,52,60,63,88,29,44,29,63,2,7,29,127,2,27,15,11,16,59,36,10,21,6,47,5,9,21,22,4,39,2,4,0,13,13,26,2,13,2,18,5,3,3,2,5,5,13,6,3,5,14,18,15,4,29,12,64,6,85,2,0,15,16,2,2,38,0,12,1,38,26,164,10,1,8,15
3,4,12,16,24,15,6,8,24,1,2,10,9,5,4,12,5,3,7,17,44,21,5,18,31,14,53,19,3,18,4,24,18,34,45,74,9,21,52,35,89,8,2,55,1,32,4,13,32,28,59,49,94,97,25,75,30,93,46,13,21,19,76,6,7,14,4,52,59,25,9,90,36,4,8,2,1,4,11,98,2,0,2,11,0,9,3,35,8,49,26,19,4,19,28,1,2,120,63,10,12,22,18,15,5,50,12,66,4,53,5,6,29,80,10,2,0,8,65,19,53,34,16,24,16,14,1,27,6,62,49,15,10,3,46,7,46,0,10,99,5,96,92,6,5,20,57,1,12,3,20,7,2,1,31,18,12,2,76,89,6,21,32,88,6,4,19,2,46,1,23,35,10,65,54,60,63,88,29,46,30,64,2,7,29,127,2,27,15,11,16,59,36,10,21,6,48,5,9,21,22,4,40,2,4,0,13,13,26,2,12,2,18,5,3,3,2,5,5,13,6,3,5,14,18,15,4,31,12,66,6,89,2,0,15,17,2,2,37,0,12,1,38,26,166,10,1,8,15
4,5,12,16,24,15,6,8,24,1,2,10,9,5,4,12,5,3,7,17,44,21,5,17,31,14,53,19,3,18,4,24,18,34,45,74,9,21,52,36,88,8,2,57,1,32,4,13,32,28,59,49,94,96,25,75,30,93,46,13,21,19,76,6,8,14,5,52,59,25,9,91,36,4,10,2,1,5,11,100,2,0,2,11,0,9,3,36,8,51,26,19,4,20,28,1,2,120,62,10,12,22,18,15,5,50,12,66,4,53,5,6,29,80,11,2,0,8,66,19,53,34,16,24,16,14,1,27,6,62,49,15,10,3,46,7,46,0,10,99,5,97,92,6,5,20,58,1,13,3,23,7,2,1,33,18,12,2,76,90,6,21,32,88,6,4,19,2,47,1,23,35,10,65,56,60,63,88,29,46,31,64,2,7,29,127,2,27,15,11,16,59,37,10,21,6,48,5,9,21,22,4,40,2,4,0,13,13,27,2,12,2,18,5,3,3,2,5,5,13,6,3,5,14,18,15,4,31,12,70,6,92,2,0,15,17,2,2,37,0,12,1,38,26,168,10,1,8,15

In [8]:
volume.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,2.858333,5.907222,6.478889,5.145,2.286667,3.048889,5.526111,0.381111,0.762222,3.811111,2.286667,1.905556,1.143333,2.667778,1.905556,1.143333,2.286667,6.478889,9.337222,6.288333,1.905556,2.096111,7.622222,5.335556,15.435000,2.286667,0.381111,23.030000,1.524444,4.001667,5.934444,1.905556,11.814444,28.011667,3.048889,8.003333,16.197222,159.358889,30.298333,0.381111,0.0,8.057778,0.381111,28.474444,1.143333,4.954444,9.337222,11.623889,10.671111,5.145,34.681111,61.522222,16.877778,25.915556,9.337222,25.725000,15.816111,4.954444,8.003333,7.241111,352.527778,2.667778,49.816667,5.335556,1.524444,18.483889,20.008333,38.383333,3.43,604.333333,1.905556,1.524444,19.6,16.333333,0.0,1.524444,4.192222,430.220000,8.166667,0.0,0.762222,3.43,0.0,3.43,0.381111,177.543333,3.048889,251.914444,9.908889,46.168889,1.333889,14.373333,7.622222,0.381111,0.762222,25.915556,20.961111,3.92,3.239444,167.743333,4.382778,4.573333,1.905556,9.582222,40.833333,46.795000,1.524444,14.101111,3.43,14.210000,39.581111,30.107778,39.200000,0.762222,0.0,2.667778,155.166667,7.241111,18.674444,8.384444,4.763889,18.293333,196.0,3.048889,0.381111,8.765556,1.715,26.786667,17.15,6.097778,36.695556,1.143333,182.497778,0.381111,14.482222,0.0,2.477222,26.677778,1.715,23.264111,73.554444,2.286667,1.905556,7.622222,20.961111,0.0,45.733333,0.762222,71.866667,1.715,0.762222,0.381111,74.153333,6.097778,4.573333,0.381111,31.060556,34.109444,2.286667,7.241111,11.814444,32.775556,2.286667,1.524444,4.573333,0.381111,17.150000,0.0,6.669444,11.814444,1.333889,23.438333,129.223889,16.197222,20.198889,26.868333,9.527778,188.976667,45.733333,27.140556,0.0,2.667778,6.097778,51.45,0.762222,9.337222,3.048889,3.239444,5.716667,17.748889,10.861667,0.381111,5.335556,2.286667,14.482222,1.905556,0.0,8.003333,5.907222,0.762222,23.383889,0.762222,0.571667,0.0,4.192222,4.382778,31.033333,0.762222,4.573333,0.762222,5.716667,1.715,0.571667,1.143333,0.190556,1.524444,1.905556,4.573333,2.286667,0.0,1.524444,3.811111,4.573333,5.907222,1.524444,105.676667,1.905556,357.808889,2.286667,202.315556,0.762222,0.0,2.858333,4.192222,0.762222,0.0,11.433333,0.0,2.286667,0.381111,12.195556,8.956111,240.236111,5.335556,0.381111,2.286667,2.096111
1,2,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,11.666667,8.166667,23.625000,3.500000,0.583333,35.250000,2.333333,6.125000,9.083333,2.916667,18.083333,42.875000,5.069167,12.250000,24.791667,243.916667,46.375000,0.583333,0.0,12.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.333333,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,39.375000,24.208333,7.583333,12.250000,11.083333,539.583333,4.083333,76.250000,8.166667,2.333333,28.291667,30.625000,58.750000,5.25,925.000000,2.916667,2.333333,30.0,25.000000,0.0,2.333333,6.416667,658.500000,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,271.750000,4.666667,385.583333,15.166667,70.666667,2.041667,22.000000,11.666667,0.583333,1.166667,39.666667,32.083333,6.00,4.958333,256.750000,6.708333,7.000000,2.916667,14.666667,62.500000,71.625000,2.333333,21.583333,5.25,21.750000,60.583333,46.083333,60.000000,1.166667,0.0,4.083333,237.500000,11.083333,28.583333,12.833333,7.291667,28.000000,300.0,4.666667,0.583333,13.416667,2.625,41.000000,26.25,9.333333,56.166667,1.750000,279.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,35.608333,112.583333,3.500000,2.916667,11.666667,32.083333,0.0,70.000000,1.166667,110.000000,2.625,1.166667,0.583333,113.500000,9.333333,7.000000,0.583333,47.541667,52.208333,3.500000,11.083333,18.083333,50.166667,3.500000,2.333333,7.000000,0.583333,26.250000,0.0,10.208333,18.083333,2.041667,35.875000,197.791667,24.791667,30.916667,41.125000,14.583333,289.250000,70.000000,41.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,16.625000,0.583333,8.166667,3.500000,22.166667,2.916667,0.0,12.250000,9.041667,1.166667,35.791667,1.166667,0.875000,0.0,6.416667,6.708333,47.500000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,9.041667,2.333333,161.750000,2.916667,547.666667,3.500000,309.666667,1.166667,0.0,4.375000,6.416667,1.166667,0.0,17.500000,0.0,3.500000,0.583333,18.666667,13.708333,367.708333,8.166667,0.583333,3.500000,3.208333
2,3,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,11.666667,8.166667,23.625000,3.500000,0.583333,63.252500,2.333333,6.125000,9.083333,2.916667,18.083333,43.277500,5.250000,12.250000,24.791667,243.916667,46.375000,0.583333,0.0,198.633333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.333333,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,39.375000,24.208333,7.583333,12.250000,11.083333,539.583333,4.083333,76.250000,8.166667,2.333333,28.291667,30.625000,58.750000,5.25,925.000000,2.916667,2.333333,30.0,25.000000,0.0,2.333333,6.416667,658.500000,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,271.750000,4.666667,385.583333,15.166667,70.666667,2.041667,22.000000,11.666667,0.583333,1.166667,39.666667,32.083333,6.00,4.958333,256.750000,6.708333,7.000000,2.916667,14.666667,62.500000,71.625000,2.333333,21.583333,5.25,21.750000,60.583333,46.083333,60.000000,1.166667,0.0,4.083333,237.500000,11.083333,28.583333,12.833333,7.291667,28.000000,300.0,4.666667,0.583333,13.416667,2.625,41.000000,26.25,9.333333,56.166667,1.750000,279.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,35.608333,112.583333,3.500000,2.916667,11.666667,32.485833,0.0,70.000000,1.166667,110.000000,2.625,1.166667,0.583333,154.900000,9.333333,7.000000,0.583333,47.541667,52.208333,3.500000,11.083333,18.083333,50.166667,3.500000,2.333333,7.000000,0.583333,26.250000,0.0,10.208333,18.083333,2.041667,35.875000,197.791667,24.791667,30.916667,41.125000,14.583333,289.250000,70.000000,41.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,16.625000,0.583333,8.166667,3.500000,22.166667,2.916667,0.0,12.250000,9.041667,1.166667,35.791667,1.166667,0.875000,0.0,6.416667,6.708333,52.330000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.639167,2.333333,161.750000,2.916667,676.466667,3.500000,309.666667,1.166667,0.0,4.375000,6.416667,1.166667,0.0,17.500000,0.0,3.500000,0.583333,18.666667,13.708333,367.708333,8.166667,0.583333,3.500000,3.208333
3,4,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,12.071111,8.166667,24.029444,3.904444,0.583333,75.833333,2.333333,6.125000,9.083333,3.321111,18.487778,43.053889,5.250000,12.250000,24.387222,278.583333,45.566111,0.583333,0.0,282.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.737778,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,40.183889,24.208333,7.583333,12.250000,11.083333,570.783333,4.083333,85.494444,8.166667,2.333333,31.758333,30.625000,58.750000,5.25,990.866667,6.383333,2.333333,40.4,25.000000,0.0,2.333333,6.416667,732.455556,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,306.416667,4.666667,486.116667,15.166667,70.666667,2.041667,32.400000,11.666667,0.583333,1.166667,39.666667,31.274444,6.00,4.958333,287.950000,6.708333,7.000000,2.916667,11.200000,62.500000,80.291667,2.333333,21.583333,5.25,14.816667,67.516667,46.083333,87.733333,1.166667,0.0,4.083333,248.708889,11.083333,28.583333,12.833333,7.696111,28.000000,300.0,5.071111,0.583333,15.034444,2.625,41.000000,26.25,8.928889,56.166667,1.750000,300.133333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,36.012778,132.574444,3.500000,2.916667,11.666667,32.666667,0.0,97.733333,0.762222,207.066667,2.625,1.166667,0.583333,173.500000,9.333333,7.000000,0.583333,47.946111,53.826111,3.500000,11.083333,18.487778,50.571111,3.500000,2.333333,7.404444,0.583333,27.058889,0.0,10.208333,18.892222,2.041667,35.875000,232.458333,24.791667,30.916667,41.125000,14.583333,361.761111,76.933333,48.475000,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,17.433889,0.583333,8.166667,3.500000,22.571111,2.916667,0.0,12.250000,9.446111,1.166667,35.993889,1.166667,0.875000,0.0,6.416667,6.708333,54.500000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.458333,2.333333,203.350000,2.916667,734.333333,3.500000,384.026667,1.166667,0.0,4.375000,6.821111,1.166667,0.0,17.095556,0.0,3.500000,0.583333,18.666667,13.708333,426.641667,8.166667,0.583333,3.500000,3.208333
4,5,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,12.250000,8.166667,24.208333,4.083333,0.583333,75.434722,2.333333,6.125000,9.083333,3.500000,18.666667,42.875000,5.250000,12.250000,24.208333,293.916667,45.208333,0.583333,0.0,282.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.916667,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,40.541667,24.208333,7.583333,12.250000,11.083333,584.583333,4.083333,89.583333,8.166667,2.731944,33.291667,30.625000,58.750000,5.25,1020.000000,7.916667,2.333333,45.0,25.000000,0.0,2.333333,6.416667,765.166667,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,321.750000,4.666667,530.583333,15.166667,70.666667,2.041667,37.000000,11.666667,0.583333,1.166667,39.666667,30.916667,6.00,4.958333,301.750000,6.708333,7.000000,2.916667,9.666667,62.500000,84.125000,2.333333,21.583333,5.25,11.750000,70.583333,46.083333,100.000000,1.166667,0.0,4.083333,253.666667,11.083333,28.583333,12.833333,7.875000,28.000000,300.0,5.250000,0.583333,15.750000,2.625,41.000000,26.25,8.750000,56.166667,1.750000,309.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,36.191667,141.416667,3.500000,2.916667,11.666667,33.065278,0.0,110.000000,0.583333,250.000000,2.625,1.166667,0.583333,194.000000,9.333333,7.000000,0.583333,48.125000,54.541667,3.500000,11.083333,18.666667,50.750000,3.500000,2.333333,7.583333,0.583333,27.416667,0.0,10.208333,19.250000,2.041667,35.875000,247.791667,24.791667,30.916667,41.125000,14.583333,393.833333,80.000000,51.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,17.791667,0.583333,8.166667,3.500000,22.750000,2.916667,0.0,12.250000,9.625000,1.166667,36.083333,1.166667,0.875000,0.0,6.416667,6.708333,59.283333,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.458333,2.333333,221.750000,2.916667,770.777778,3.500000,416.916667,1.166667,0.0,4.375000,7.000000,1.166667,0.0,16.916667,0.0,3.500000,0.583333,18.666667,13.708333,452.708333,8.166667,0.583333,3.500000,3.208333

In [9]:
price.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,1.02,1.075556,1.01125,1.17,1.05061,1.35,1,0.863333,0.989,1.082463,1.057727,1.09,0.999625,0.74559,0.775,1.025333,0.951,0.985,0.75,1.2,1.0362,0.98335,1.038182,0.928571,0.910526,0.96,0.7,0.882814,0.861429,1.0376,1.18,0.76,0.67988,0.99,0.505,1,1.1,0.928,1.034,1.003333,1.029917,0.815,0.846373,0.67,0.833325,0.98625,1.17,1.17,0.72,0.87775,0.8,0.647143,1.2,0.633333,1.075,0.8,1.146667,0.8074,0.77373,0.7981,0.2705,0.71,1.28,0.31,0.3,0.3029,0.923333,0.933333,0.4894,0.39,1,0.95,0.906667,1.2,1.2,0.72,0.755,1.014286,0.755,0.72,0.55776,0.8,0.831878,1.003333,1.25,0.7,0.982667,0.9325,1.028571,1.004333,0.776667,0.972857,1.017143,0.72,0.903333,0.4522,0.734129,0.72,0.98375,1,0.89,0.586667,1.016667,0.31,0.766667,1.2,0.673333,0.681,0.895,0.791429,0.78,1.18,0.8,0.27,0.5612,1.2,0.717,1.05,0.6211,1.025829,1.2425,0.81,0.98,0.636667,0.925,0.8318,0.8,1.03,0.68428,0.72,0.9625,0.658,0.97,0.91,0.7,0.70535,1.1,1.1612,1.3,0.3,1.183333,0.725,1.175,0.7675,1.1,0.783333,0.86,0.94,0.8465,0.94,1.126,1.024,0.76994,0.9,1,0.865,0.81,0.6396,1.0028,0.992667,1.038,0.64,0.90125,0.8978,0.894267,0.948615,0.88619,1.1,0.901333,0.25,0.726218,1.2,0.72,0.9,0.775775,1.18,0.9975,1.103571,1.16625,1.0875,0.977778,1.14,0.821,1.0925,1.34,0.902857,1.03,0.858,0.865,1.093333,1.155,0.8084,1.26,0.75,1.2,1.186,1.113333,1.034444,0.79,1.002857,0.993333,0.980714,0.973333,1.0025,1.05875,1.2,1.06,1.16,0.85,0.9,1.047778,1.013333,0.938,0.98055,0.892,0.98375,0.866,1.333333,0.485,1.0375,0.938938,0.88,0.846667,0.991429,0.975,0.9,1.112,0.96,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425
1,2,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,1.02,1.075556,1.01125,1.17,1.05061,1.35,1,0.863333,0.989,1.082463,1.057727,1.09,0.999625,0.74559,0.775,1.025333,0.951,0.985,0.75,1.2,1.0362,0.98335,1.038182,0.928571,0.910526,0.96,0.7,0.882814,0.861429,1.0376,1.18,0.76,0.67988,0.99,0.505,1,1.1,0.928,1.034,1.003333,1.029917,0.815,0.846373,0.67,0.833325,0.98625,1.17,1.17,0.72,0.87775,0.8,0.647143,1.2,0.633333,1.075,0.8,1.146667,0.8074,0.77373,0.7981,0.2705,0.71,1.28,0.31,0.3,0.3029,0.923333,0.933333,0.4894,0.39,1,0.95,0.906667,1.2,1.2,0.72,0.755,1.014286,0.755,0.72,0.55776,0.8,0.831878,1.003333,1.25,0.7,0.982667,0.9325,1.028571,1.004333,0.776667,0.972857,1.017143,0.72,0.903333,0.4522,0.734129,0.72,0.98375,1,0.89,0.586667,1.016667,0.31,0.766667,1.2,0.673333,0.681,0.895,0.791429,0.78,1.18,0.8,0.27,0.5612,1.2,0.717,1.05,0.6211,1.025829,1.2425,0.81,0.98,0.636667,0.925,0.8318,0.8,1.03,0.68428,0.72,0.9625,0.658,0.97,0.91,0.7,0.70535,1.1,1.1612,1.3,0.3,1.183333,0.725,1.175,0.7675,1.1,0.783333,0.86,0.94,0.8465,0.94,1.126,1.024,0.76994,0.9,1,0.865,0.81,0.6396,1.0028,0.992667,1.038,0.64,0.90125,0.8978,0.894267,0.948615,0.88619,1.1,0.901333,0.25,0.726218,1.2,0.72,0.9,0.775775,1.18,0.9975,1.103571,1.16625,1.0875,0.977778,1.14,0.821,1.0925,1.34,0.902857,1.03,0.858,0.865,1.093333,1.155,0.8084,1.26,0.75,1.2,1.186,1.113333,1.034444,0.79,1.002857,0.993333,0.980714,0.973333,1.0025,1.05875,1.2,1.06,1.16,0.85,0.9,1.047778,1.013333,0.938,0.98055,0.892,0.98375,0.866,1.333333,0.485,1.0375,0.938938,0.88,0.846667,0.991429,0.975,0.9,1.112,0.96,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425
2,3,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,1.02,1.075556,1.01125,1.17,1.05061,1.35,1,0.863333,0.989,1.082463,1.057727,1.09,0.999625,0.74559,0.775,1.025333,0.951,0.985,0.75,1.2,1.0362,0.98335,1.038182,0.928571,0.910526,0.96,0.7,0.882814,0.861429,1.0376,1.18,0.76,0.67988,0.99,0.505,1,1.1,0.928,1.034,1.003333,1.029917,0.815,0.846373,0.67,0.833325,0.98625,1.17,1.17,0.72,0.87775,0.8,0.647143,1.2,0.633333,1.075,0.8,1.146667,0.8074,0.77373,0.7981,0.2705,0.71,1.28,0.31,0.3,0.3029,0.923333,0.933333,0.4894,0.39,1,0.95,0.906667,1.2,1.2,0.72,0.755,1.014286,0.755,0.72,0.55776,0.8,0.831878,1.003333,1.25,0.7,0.982667,0.9325,1.028571,1.004333,0.776667,0.972857,1.017143,0.72,0.903333,0.4522,0.734129,0.72,0.98375,1,0.89,0.586667,1.016667,0.31,0.766667,1.2,0.673333,0.681,0.895,0.791429,0.78,1.18,0.8,0.27,0.5612,1.2,0.717,1.05,0.6211,1.025829,1.2425,0.81,0.98,0.636667,0.925,0.8318,0.8,1.03,0.68428,0.72,0.9625,0.658,0.97,0.91,0.7,0.70535,1.1,1.1612,1.3,0.3,1.183333,0.725,1.175,0.7675,1.1,0.783333,0.86,0.94,0.8465,0.94,1.126,1.024,0.76994,0.9,1,0.865,0.81,0.6396,1.0028,0.992667,1.038,0.64,0.90125,0.8978,0.894267,0.948615,0.88619,1.1,0.901333,0.25,0.726218,1.2,0.72,0.9,0.775775,1.18,0.9975,1.103571,1.16625,1.0875,0.977778,1.14,0.821,1.0925,1.34,0.902857,1.03,0.858,0.865,1.093333,1.155,0.8084,1.26,0.75,1.2,1.186,1.113333,1.034444,0.79,1.002857,0.993333,0.980714,0.973333,1.0025,1.05875,1.2,1.06,1.16,0.85,0.9,1.047778,1.013333,0.938,0.98055,0.892,0.98375,0.866,1.333333,0.485,1.0375,0.938938,0.88,0.846667,0.991429,0.975,0.9,1.112,0.96,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425
3,4,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,1.02,1.075556,1.01125,1.17,1.05061,1.35,1,0.863333,0.989,1.082463,1.057727,1.09,0.999625,0.74559,0.775,1.025333,0.951,0.985,0.75,1.2,1.0362,0.98335,1.038182,0.928571,0.910526,0.96,0.7,0.882814,0.861429,1.0376,1.18,0.76,0.67988,0.99,0.505,1,1.1,0.928,1.034,1.003333,1.029917,0.815,0.846373,0.67,0.833325,0.98625,1.17,1.17,0.72,0.87775,0.8,0.647143,1.2,0.633333,1.075,0.8,1.146667,0.8074,0.77373,0.7981,0.2705,0.71,1.28,0.31,0.3,0.3029,0.923333,0.933333,0.4894,0.39,1,0.95,0.906667,1.2,1.2,0.72,0.755,1.014286,0.755,0.72,0.55776,0.8,0.831878,1.003333,1.25,0.7,0.982667,0.9325,1.028571,1.004333,0.776667,0.972857,1.017143,0.72,0.903333,0.4522,0.734129,0.72,0.98375,1,0.89,0.586667,1.016667,0.31,0.766667,1.2,0.673333,0.681,0.895,0.791429,0.78,1.18,0.8,0.27,0.5612,1.2,0.717,1.05,0.6211,1.025829,1.2425,0.81,0.98,0.636667,0.925,0.8318,0.8,1.03,0.68428,0.72,0.9625,0.658,0.97,0.91,0.7,0.70535,1.1,1.1612,1.3,0.3,1.183333,0.725,1.175,0.7675,1.1,0.783333,0.86,0.94,0.8465,0.94,1.126,1.024,0.76994,0.9,1,0.865,0.81,0.6396,1.0028,0.992667,1.038,0.64,0.90125,0.8978,0.894267,0.948615,0.88619,1.1,0.901333,0.25,0.726218,1.2,0.72,0.9,0.775775,1.18,0.9975,1.103571,1.16625,1.0875,0.977778,1.14,0.821,1.0925,1.34,0.902857,1.03,0.858,0.865,1.093333,1.155,0.8084,1.26,0.75,1.2,1.186,1.113333,1.034444,0.79,1.002857,0.993333,0.980714,0.973333,1.0025,1.05875,1.2,1.06,1.16,0.85,0.9,1.047778,1.013333,0.938,0.98055,0.892,0.98375,0.866,1.333333,0.485,1.0375,0.938938,0.88,0.846667,0.991429,0.975,0.9,1.112,0.96,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425
4,5,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,1.02,1.075556,1.01125,1.17,1.05061,1.35,1,0.863333,0.989,1.082463,1.057727,1.09,0.999625,0.74559,0.775,1.025333,0.951,0.985,0.75,1.2,1.0362,0.98335,1.038182,0.928571,0.910526,0.96,0.7,0.882814,0.861429,1.0376,1.18,0.76,0.67988,0.99,0.505,1,1.1,0.928,1.034,1.003333,1.029917,0.815,0.846373,0.67,0.833325,0.98625,1.17,1.17,0.72,0.87775,0.8,0.647143,1.2,0.633333,1.075,0.8,1.146667,0.8074,0.77373,0.7981,0.2705,0.71,1.28,0.31,0.3,0.3029,0.923333,0.933333,0.4894,0.39,1,0.95,0.906667,1.2,1.2,0.72,0.755,1.014286,0.755,0.72,0.55776,0.8,0.831878,1.003333,1.25,0.7,0.982667,0.9325,1.028571,1.004333,0.776667,0.972857,1.017143,0.72,0.903333,0.4522,0.734129,0.72,0.98375,1,0.89,0.586667,1.016667,0.31,0.766667,1.2,0.673333,0.681,0.895,0.791429,0.78,1.18,0.8,0.27,0.5612,1.2,0.717,1.05,0.6211,1.025829,1.2425,0.81,0.98,0.636667,0.925,0.8318,0.8,1.03,0.68428,0.72,0.9625,0.658,0.97,0.91,0.7,0.70535,1.1,1.1612,1.3,0.3,1.183333,0.725,1.175,0.7675,1.1,0.783333,0.86,0.94,0.8465,0.94,1.126,1.024,0.76994,0.9,1,0.865,0.81,0.6396,1.0028,0.992667,1.038,0.64,0.90125,0.8978,0.894267,0.948615,0.88619,1.1,0.901333,0.25,0.726218,1.2,0.72,0.9,0.775775,1.18,0.9975,1.103571,1.16625,1.0875,0.977778,1.14,0.821,1.0925,1.34,0.902857,1.03,0.858,0.865,1.093333,1.155,0.8084,1.26,0.75,1.2,1.186,1.113333,1.034444,0.79,1.002857,0.993333,0.980714,0.973333,1.0025,1.05875,1.2,1.06,1.16,0.85,0.9,1.047778,1.013333,0.938,0.98055,0.892,0.98375,0.866,1.333333,0.485,1.0375,0.938938,0.88,0.846667,0.991429,0.975,0.9,1.112,0.96,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425

In [10]:
duration.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,0.49,0.871111,0.98,0.762222,0.326667,0.381111,0.98,0.054444,0.108889,0.544444,0.326667,0.272222,0.163333,0.381111,0.272222,0.163333,0.326667,0.925556,2.232222,0.98,0.272222,0.435556,1.088889,0.762222,2.504444,0.435556,0.054444,0.653333,0.217778,0.598889,0.435556,0.326667,1.851111,3.920000,0.435556,1.143333,2.504444,1.633333,4.464444,0.108889,0.0,0.272222,0.054444,1.197778,0.217778,0.707778,1.633333,1.197778,1.524444,0.925556,4.954444,2.123333,0.762222,3.702222,1.633333,3.756667,1.96,0.707778,1.143333,1.034444,3.702222,0.326667,0.326667,0.762222,0.217778,2.722222,2.94,1.197778,0.49,4.083333,0.272222,0.217778,0.326667,0.108889,0.0,0.217778,0.598889,4.518889,0.054444,0.0,0.108889,0.49,0.0,0.49,0.054444,1.633333,0.435556,2.014444,1.415556,1.034444,0.217778,0.816667,1.143333,0.054444,0.108889,3.702222,3.212222,0.381111,0.653333,1.088889,0.653333,0.707778,0.272222,0.544444,0.272222,3.538889,0.217778,2.395556,0.272222,0.272222,0.381111,4.301111,0.381111,0.108889,0.0,0.381111,2.940000,1.034444,2.667778,1.197778,0.762222,1.306667,0.816667,0.435556,0.054444,1.252222,0.326667,3.375556,2.177778,0.871111,0.435556,0.163333,2.341111,0.054444,2.068889,0.0,0.381111,4.954444,0.272222,3.756667,4.410000,0.326667,0.272222,1.088889,2.994444,0.0,0.490000,0.108889,0.598889,0.272222,0.108889,0.054444,0.925556,0.925556,0.653333,0.054444,4.028889,4.736667,0.326667,1.034444,1.687778,4.682222,0.326667,0.217778,0.653333,0.054444,2.450000,0.0,1.143333,1.796667,0.217778,3.375556,2.722222,3.157778,3.157778,4.246667,1.361111,2.286667,0.381111,2.885556,0.0,0.381111,1.143333,6.805556,0.108889,1.361111,0.435556,0.544444,0.816667,2.341111,1.687778,0.108889,0.762222,0.326667,2.450000,0.272222,0.0,1.143333,0.980000,0.108889,1.470000,0.108889,0.163333,0.0,0.598889,0.653333,0.653333,0.108889,0.653333,0.108889,0.816667,0.272222,0.108889,0.163333,0.054444,0.217778,0.272222,0.653333,0.326667,0.0,0.217778,0.544444,0.653333,0.871111,0.217778,1.034444,0.326667,2.068889,0.326667,3.321111,0.108889,0.0,0.435556,0.598889,0.108889,0.0,1.905556,0.0,0.326667,0.054444,1.905556,1.306667,8.493333,0.544444,0.054444,0.435556,0.326667
1,2,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.666667,1.166667,3.833333,0.666667,0.083333,1.000000,0.333333,0.916667,0.666667,0.500000,2.833333,6.000000,0.724167,1.750000,3.833333,2.500000,6.833333,0.166667,0.0,0.416667,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.333333,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.750000,3.00,1.083333,1.750000,1.583333,5.666667,0.500000,0.500000,1.166667,0.333333,4.166667,4.50,1.833333,0.75,6.250000,0.416667,0.333333,0.500000,0.166667,0.0,0.333333,0.916667,6.916667,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.500000,0.666667,3.083333,2.166667,1.583333,0.333333,1.250000,1.750000,0.083333,0.166667,5.666667,4.916667,0.583333,1.000000,1.666667,1.000000,1.083333,0.416667,0.833333,0.416667,5.416667,0.333333,3.666667,0.416667,0.416667,0.583333,6.583333,0.583333,0.166667,0.0,0.583333,4.500000,1.583333,4.083333,1.833333,1.166667,2.000000,1.250000,0.666667,0.083333,1.916667,0.500000,5.166667,3.333333,1.333333,0.666667,0.250000,3.583333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.750000,6.750000,0.500000,0.416667,1.666667,4.583333,0.0,0.750000,0.166667,0.916667,0.416667,0.166667,0.083333,1.416667,1.416667,1.000000,0.083333,6.166667,7.250000,0.500000,1.583333,2.583333,7.166667,0.500000,0.333333,1.000000,0.083333,3.750000,0.0,1.750000,2.750000,0.333333,5.166667,4.166667,4.833333,4.833333,6.500000,2.083333,3.500000,0.583333,4.416667,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.583333,0.166667,1.166667,0.500000,3.750000,0.416667,0.0,1.750000,1.500000,0.166667,2.250000,0.166667,0.250000,0.0,0.916667,1.000000,1.000000,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.333333,0.333333,1.583333,0.500000,3.166667,0.500000,5.083333,0.166667,0.0,0.666667,0.916667,0.166667,0.0,2.916667,0.0,0.500000,0.083333,2.916667,2.000000,13.000000,0.833333,0.083333,0.666667,0.500000
2,3,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.666667,1.166667,3.833333,0.666667,0.083333,1.287500,0.333333,0.916667,0.666667,0.500000,2.833333,6.057500,0.750000,1.750000,3.833333,2.500000,6.833333,0.166667,0.0,1.336667,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.333333,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.750000,3.00,1.083333,1.750000,1.583333,5.666667,0.500000,0.500000,1.166667,0.333333,4.166667,4.50,1.833333,0.75,6.250000,0.416667,0.333333,0.500000,0.166667,0.0,0.333333,0.916667,6.916667,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.500000,0.666667,3.083333,2.166667,1.583333,0.333333,1.250000,1.750000,0.083333,0.166667,5.666667,4.916667,0.583333,1.000000,1.666667,1.000000,1.083333,0.416667,0.833333,0.416667,5.416667,0.333333,3.666667,0.416667,0.416667,0.583333,6.583333,0.583333,0.166667,0.0,0.583333,4.500000,1.583333,4.083333,1.833333,1.166667,2.000000,1.250000,0.666667,0.083333,1.916667,0.500000,5.166667,3.333333,1.333333,0.666667,0.250000,3.583333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.750000,6.750000,0.500000,0.416667,1.666667,4.640833,0.0,0.750000,0.166667,0.916667,0.416667,0.166667,0.083333,1.761667,1.416667,1.000000,0.083333,6.166667,7.250000,0.500000,1.583333,2.583333,7.166667,0.500000,0.333333,1.000000,0.083333,3.750000,0.0,1.750000,2.750000,0.333333,5.166667,4.166667,4.833333,4.833333,6.500000,2.083333,3.500000,0.583333,4.416667,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.583333,0.166667,1.166667,0.500000,3.750000,0.416667,0.0,1.750000,1.500000,0.166667,2.250000,0.166667,0.250000,0.0,0.916667,1.000000,1.057500,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.275833,0.333333,1.583333,0.500000,3.914167,0.500000,5.083333,0.166667,0.0,0.666667,0.916667,0.166667,0.0,2.916667,0.0,0.500000,0.083333,2.916667,2.000000,13.000000,0.833333,0.083333,0.666667,0.500000
3,4,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.724444,1.166667,3.891111,0.724444,0.083333,1.416667,0.333333,0.916667,0.666667,0.557778,2.891111,6.025556,0.750000,1.750000,3.775556,2.731111,6.717778,0.166667,0.0,1.750000,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.391111,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.865556,3.00,1.083333,1.750000,1.583333,5.897778,0.500000,0.557778,1.166667,0.333333,4.224444,4.50,1.833333,0.75,6.712222,0.474444,0.333333,0.673333,0.166667,0.0,0.333333,0.916667,7.494444,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.788889,0.666667,3.834444,2.166667,1.583333,0.333333,1.365556,1.750000,0.083333,0.166667,5.666667,4.801111,0.583333,1.000000,1.840000,1.000000,1.083333,0.416667,0.775556,0.416667,5.474444,0.333333,3.666667,0.416667,0.358889,0.641111,6.583333,0.814444,0.166667,0.0,0.583333,4.788889,1.583333,4.083333,1.833333,1.224444,2.000000,1.250000,0.724444,0.083333,2.147778,0.500000,5.166667,3.333333,1.275556,0.666667,0.250000,3.756667,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.807778,6.807778,0.500000,0.416667,1.666667,4.666667,0.0,0.981111,0.108889,1.378889,0.416667,0.166667,0.083333,1.916667,1.416667,1.000000,0.083333,6.224444,7.423333,0.500000,1.583333,2.641111,7.224444,0.500000,0.333333,1.057778,0.083333,3.865556,0.0,1.750000,2.865556,0.333333,5.166667,4.455556,4.833333,4.833333,6.500000,2.083333,3.904444,0.641111,4.474444,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.698889,0.166667,1.166667,0.500000,3.807778,0.416667,0.0,1.750000,1.557778,0.166667,2.307778,0.166667,0.250000,0.0,0.916667,1.000000,1.083333,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.250000,0.333333,1.930000,0.500000,4.250000,0.500000,5.892222,0.166667,0.0,0.666667,0.974444,0.166667,0.0,2.858889,0.0,0.500000,0.083333,2.916667,2.000000,13.288889,0.833333,0.083333,0.666667,0.500000
4,5,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.750000,1.166667,3.916667,0.750000,0.083333,1.359722,0.333333,0.916667,0.666667,0.583333,2.916667,6.000000,0.750000,1.750000,3.750000,2.833333,6.666667,0.166667,0.0,1.750000,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.416667,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.916667,3.00,1.083333,1.750000,1.583333,6.000000,0.500000,0.583333,1.166667,0.390278,4.250000,4.50,1.833333,0.75,6.916667,0.500000,0.333333,0.750000,0.166667,0.0,0.333333,0.916667,7.750000,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.916667,0.666667,4.166667,2.166667,1.583333,0.333333,1.416667,1.750000,0.083333,0.166667,5.666667,4.750000,0.583333,1.000000,1.916667,1.000000,1.083333,0.416667,0.750000,0.416667,5.500000,0.333333,3.666667,0.416667,0.333333,0.666667,6.583333,0.916667,0.166667,0.0,0.583333,4.916667,1.583333,4.083333,1.833333,1.250000,2.000000,1.250000,0.750000,0.083333,2.250000,0.500000,5.166667,3.333333,1.250000,0.666667,0.250000,3.833333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.833333,6.833333,0.500000,0.416667,1.666667,4.723611,0.0,1.083333,0.083333,1.583333,0.416667,0.166667,0.083333,2.087500,1.416667,1.000000,0.083333,6.250000,7.500000,0.500000,1.583333,2.666667,7.250000,0.500000,0.333333,1.083333,0.083333,3.916667,0.0,1.750000,2.916667,0.333333,5.166667,4.583333,4.833333,4.833333,6.500000,2.083333,4.083333,0.666667,4.500000,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.750000,0.166667,1.166667,0.500000,3.833333,0.416667,0.0,1.750000,1.583333,0.166667,2.333333,0.166667,0.250000,0.0,0.916667,1.000000,1.140278,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.250000,0.333333,2.083333,0.500000,4.477778,0.500000,6.250000,0.166667,0.0,0.666667,1.000000,0.166667,0.0,2.833333,0.0,0.500000,0.083333,2.916667,2.000000,13.416667,0.833333,0.083333,0.666667,0.500000

In [11]:
stations.head()

   station_id   latitude   longitude  fast  slow  count
0           1  22.716272  113.826349     5     5     10
1           2  22.678851  114.049721    20     0     20
2           3  22.509541  114.058510     0     8      8
3           4  22.605970  114.122110     0     6      6
4           5  22.732771  113.816951     0    55     55

In [12]:
information.head()

,num,grid,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,1,102,30,3,27,0.71,114.1030,22.54041,0,0
1,3,105,93,0,93,0.77,114.1208,22.55127,0,0
2,5,107,88,2,86,0.89,114.1304,22.54486,0,0
3,6,108,39,0,39,1.26,114.1315,22.55403,0,0
4,7,109,39,0,39,3.15,114.1430,22.56388,0,0

In [13]:
time.head()

   month  day  year  hour  minute  second
0      6   19  2022     0       0       0
1      6   19  2022     0       5       0
2      6   19  2022     0      10       0
3      6   19  2022     0      15       0
4      6   19  2022     0      20       0

In [14]:
for name, df in datasets.items():
    print("\n")
    print(name)
    print(df.columns.tolist())

occupancy
['timestamp', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


volume
['timestamp', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


price
['timestamp', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


duration
['timestamp', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


stations
['station_id', 'latitude', 'longitude', 'fast', 'slow', 'count']


time
['month', 'day', 'year', 'hour', 'minute', 'second']


information
['num', 'grid', 'count', 'fast_count', 'slow_count', 'area', 'lon', 'la', 'CBD', 'dynamic_pricing']


distance
['Unnamed: 0', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


adj
['node_id', '102', '105', '107', '108', '109', '110', '111', '115', '123', '124', '202', '204', '205', '206', '208', '215', '216', '217', '223', '224', '225', '226', '227', '235', '307', '309', '320', '322', '323', '324', '325', '326', '328', '329', '330', '331', '332', '333', '335', '340', '343', '346', '347', '348', '406', '408', '501', '502', '506', '512', '513', '519', '520', '522', '525', '526', '527', '529', '552', '570', '576', '577', '580', '584', '585', '587', '588', '589', '594', '595', '596', '598', '627', '628', '630', '631', '632', '633', '636', '638', '643', '644', '655', '656', '681', '682', '686', '690', '691', '693', '698', '699', '700', '701', '702', '703', '704', '705', '706', '708', '709', '710', '711', '712', '715', '716', '719', '724', '728', '729', '732', '733', '735', '737', '739', '741', '744', '745', '746', '751', '771', '773', '775', '781', '783', '784', '790', '795', '799', '802', '804', '831', '832', '835', '842', '848', '849', '851', '852', '855', '858', '862', '883', '887', '888', '890', '891', '893', '895', '897', '900', '901', '902', '903', '904', '937', '965', '966', '967', '969', '972', '974', '975', '979', '982', '983', '986', '987', '988', '989', '991', '996', '998', '1000', '1009', '1011', '1015', '1026', '1029', '1031', '1032', '1037', '1043', '1049', '1060', '1061', '1062', '1066', '1067', '1068', '1071', '1072', '1074', '1075', '1076', '1081', '1082', '1083', '1085', '1086', '1088', '1090', '1092', '1093', '1095', '1096', '1098', '1099', '1100', '1101', '1102', '1104', '1105', '1106', '1107', '1109', '1110', '1111', '1112', '1113', '1114', '1115', '1119', '1121', '1122', '1124', '1126', '1131', '1134', '1137', '1138', '1143', '1144', '1149', '1154', '1156', '1159', '1160', '1162', '1163', '1164', '1166', '1167', '1168', '1170', '1172', '1173']


acn
['_meta', 'end', 'min_kWh', 'site', 'start', '_items', '_id', 'clusterID', 'connectionTime', 'disconnectTime', 'doneChargingTime', 'kWhDelivered', 'sessionID', 'siteID', 'spaceID', 'stationID', 'timezone', 'userID', 'userInputs', 'WhPerMile', 'kWhRequested', 'milesRequested', 'minutesAvailable', 'modifiedAt', 'paymentRequired', 'requestedDeparture', 'userID.1']

In [ ]:
missing = []

for name, df in datasets.items():
    missing.append([
        name,
        df.isnull().sum().sum()
    ])

missing_df = pd.DataFrame(
    missing,
    columns=["dataset","missing_values"]
)

missing_df

       dataset  missing_values
0    occupancy               0
1       volume               0
2        price               0
3     duration               0
4     stations               0
5         time               0
6  information               0
7     distance               0
8          adj               0
9          acn          244698

In [20]:
missing_acn = (
    acn.isnull()
       .sum()
       .sort_values(ascending=False)
)

missing_acn[missing_acn > 0]

_meta                 16304
end                   16304
min_kWh               16304
start                 16304
_items                16304
userInputs            16304
site                  16303
userID                14072
paymentRequired       12767
modifiedAt            12767
minutesAvailable      12767
requestedDeparture    12767
userID.1              12767
kWhRequested          12767
WhPerMile             12767
milesRequested        12767
doneChargingTime       1313
clusterID              1305
_id                    1305
disconnectTime         1305
connectionTime         1305
stationID              1305
timezone               1305
sessionID              1305
kWhDelivered           1305
siteID                 1305
spaceID                1305
dtype: int64

In [21]:
full_missing = acn.columns[acn.isnull().all()]

print(full_missing.tolist())

['_meta', 'end', 'min_kWh', 'start', '_items', 'userInputs']

In [22]:
acn.drop(columns=full_missing, inplace=True)

In [23]:
missing_pct = (
    acn.isnull()
       .mean()
       .sort_values(ascending=False)
       * 100
)

missing_pct = missing_pct[missing_pct > 0]

missing_pct

site                  99.993867
userID                86.310108
modifiedAt            78.305937
requestedDeparture    78.305937
paymentRequired       78.305937
userID.1              78.305937
milesRequested        78.305937
kWhRequested          78.305937
WhPerMile             78.305937
minutesAvailable      78.305937
doneChargingTime       8.053238
clusterID              8.004171
_id                    8.004171
disconnectTime         8.004171
connectionTime         8.004171
timezone               8.004171
stationID              8.004171
kWhDelivered           8.004171
sessionID              8.004171
spaceID                8.004171
siteID                 8.004171
dtype: float64

In [24]:
acn["userID"].nunique()

204

In [25]:
acn.columns.tolist()

['site',
 '_id',
 'clusterID',
 'connectionTime',
 'disconnectTime',
 'doneChargingTime',
 'kWhDelivered',
 'sessionID',
 'siteID',
 'spaceID',
 'stationID',
 'timezone',
 'userID',
 'WhPerMile',
 'kWhRequested',
 'milesRequested',
 'minutesAvailable',
 'modifiedAt',
 'paymentRequired',
 'requestedDeparture',
 'userID.1']

In [28]:
acn.info()

<class 'pandas.DataFrame'>
RangeIndex: 16304 entries, 0 to 16303
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               14999 non-null  str
 1   clusterID         14999 non-null  float64
 2   connectionTime    14999 non-null  str
 3   disconnectTime    14999 non-null  str
 4   doneChargingTime  14991 non-null  str
 5   kWhDelivered      14999 non-null  float64
 6   sessionID         14999 non-null  str
 7   siteID            14999 non-null  float64
 8   spaceID           14999 non-null  str
 9   stationID         14999 non-null  str
 10  timezone          14999 non-null  str
dtypes: float64(3), str(8)
memory usage: 1.4 MB

In [27]:
drop_cols = [
    "site",                 # 99.99% missing
    "userID",               # 86% missing
    "WhPerMile",            # 78% missing
    "kWhRequested",         # 78% missing
    "milesRequested",       # 78% missing
    "minutesAvailable",     # 78% missing
    "modifiedAt",           # 78% missing
    "paymentRequired",      # 78% missing
    "requestedDeparture",   # 78% missing
    "userID.1"              # duplicate user field
]

acn = acn.drop(columns=drop_cols)

In [29]:
date_cols = [
    "connectionTime",
    "disconnectTime",
    "doneChargingTime"
]

for col in date_cols:
    acn[col] = pd.to_datetime(acn[col], errors="coerce")

acn.info()

<class 'pandas.DataFrame'>
RangeIndex: 16304 entries, 0 to 16303
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               14999 non-null  str
 1   clusterID         14999 non-null  float64
 2   connectionTime    14999 non-null  datetime64[us]
 3   disconnectTime    14999 non-null  datetime64[us]
 4   doneChargingTime  14991 non-null  datetime64[us]
 5   kWhDelivered      14999 non-null  float64
 6   sessionID         14999 non-null  str
 7   siteID            14999 non-null  float64
 8   spaceID           14999 non-null  str
 9   stationID         14999 non-null  str
 10  timezone          14999 non-null  str
dtypes: datetime64[us](3), float64(3), str(5)
memory usage: 1.4 MB

In [30]:
acn["session_duration_hours"] = (
    acn["disconnectTime"] -
    acn["connectionTime"]
).dt.total_seconds() / 3600

In [31]:
acn["charging_duration_hours"] = (
    acn["doneChargingTime"] -
    acn["connectionTime"]
).dt.total_seconds() / 3600

In [32]:
acn[
    [
        "session_duration_hours",
        "charging_duration_hours",
        "kWhDelivered"
    ]
].describe()

       session_duration_hours  charging_duration_hours  kWhDelivered
count            14999.000000             14991.000000  14999.000000
mean                 5.923631                 3.236411      9.002466
std                  6.459457                 3.185251      7.055848
min                  0.087500                -0.689444      0.501000
25%                  2.025139                 1.271806      4.008500
50%                  4.764167                 2.241667      7.435000
75%                  8.729722                 4.244444     13.204000
max                245.269167               104.428333     69.373000

In [33]:
acn["hour"] = acn["connectionTime"].dt.hour
acn["dayofweek"] = acn["connectionTime"].dt.dayofweek
acn["month"] = acn["connectionTime"].dt.month

In [34]:
acn[
    [
        "hour",
        "dayofweek",
        "month"
    ]
].head()

   hour  dayofweek  month
0  11.0        2.0    4.0
1  13.0        2.0    4.0
2  13.0        2.0    4.0
3  14.0        2.0    4.0
4  14.0        2.0    4.0

In [35]:
acn.to_csv(
    "../data/acn/acn_cleaned.csv",
    index=False
)

print("ACN cleaned dataset saved.")

ACN cleaned dataset saved.

In [ ]:
# Key Findings

## UrbanEV Dataset

- Contains 247 charging grids observed over 8640 time intervals.
- No missing values were found.
- Occupancy, volume, duration, and price share identical structures.
- Data is recorded at 5-minute intervals.

## ACN Dataset

- Contains 16,304 charging sessions.
- Missing values are concentrated in  user-preference fields.
- Core operational charging variables remain largely complete.
- Datetime variables were converted and session-level features were created.

## Preprocessing Decisions

- Removed columns with excessive missingness (>75%).
- Retained operational charging session fields.
- Generated charging duration and session duration features.
- Saved cleaned dataset for downstream modeling.